name: genesmanproxy_example
description: Example app for DownStream package
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  genesmanproxy:
    path: ../
  video_player: ^2.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
